-- Create the CUSTOMER table
CREATE TABLE CUSTOMER (
    CustomerID INT PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100) UNIQUE,
    Phone VARCHAR2(15)
);

-- Create the PRODUCT table
CREATE TABLE PRODUCT (
    ProductID INT PRIMARY KEY,
    ProductName VARCHAR2(100) NOT NULL,
    Price NUMBER(10, 2) NOT NULL,
    StockQuantity INT NOT NULL
);

ALTER TABLE PRODUCT 
ADD Category VARCHAR2(20);


-- Create the ORDERS table
CREATE TABLE ORDERS (
    OrderID INT PRIMARY KEY,
    OrderDate DATE NOT NULL,
    CustomerID INT,
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID)
);

ALTER TABLE ORDERS 
ADD OrderDate DATE DEFAULT SYSDATE;

-- Create the ORDER_DETAILS table
CREATE TABLE ORDER_DETAILS (
    OrderDetailID INT PRIMARY KEY,
    OrderID INT,
    ProductID INT,
    Quantity INT NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID),
    FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);
